Repository moveit/moveit2, pull requests merged in 2022-06, with the labels that each got.

#1308 Decorate MoveItConfigs with dataclass
  moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py
Labels: backport-humble

#1338 Remove everything from repos
  moveit2.repos
Labels: backport-humble

#1339 Update pre-commit run on Ubuntu 22.04
  .github/workflows/format.yaml
  moveit_ros/manipulation/pick_place/src/approach_and_translate_stage.cpp
  moveit_setup_assistant/src/tools/compute_default_collisions.cpp
Labels: backport-humble

#1325 Type safety for CartesianInterpolator
  moveit_core/robot_state/include/moveit/robot_state/cartesian_interpolator.h
  moveit_core/robot_state/src/cartesian_interpolator.cpp
Labels: backport-galactic, backport-humble

#1353 Fix PlanarJointModel::satisfiesPositionBounds
  moveit_core/robot_model/src/planar_joint_model.cpp
Labels: backport-foxy, backport-galactic, backport-humble
