Repository moveit/moveit2, pull requests merged in 2022-01, with the labels that each got.

#952 Add rosdistro version to upstream ws cache prefix
  .github/workflows/ci.yaml
Labels: backport, backport-foxy

#958 fix usage of placeholder
  moveit_planners/pilz_industrial_motion_planner/src/move_group_sequence_action.cpp
Labels: backport-galactic

#971 Remove some Maintainers from Pilz Planner
  moveit_planners/pilz_industrial_motion_planner/package.xml
  moveit_planners/pilz_industrial_motion_planner_testutils/package.xml
Labels: backport-galactic

#981 :heavy_plus_sign: ament_cmake_gtest dependency
  moveit_planners/pilz_industrial_motion_planner/package.xml
Labels: backport-galactic

#957 Fix boost linking errors for Windows
  moveit_core/CMakeLists.txt
  moveit_core/distance_field/CMakeLists.txt
  moveit_core/utils/CMakeLists.txt
  moveit_ros/occupancy_map_monitor/CMakeLists.txt
  moveit_ros/perception/CMakeLists.txt
  moveit_ros/planning_interface/CMakeLists.txt
  moveit_ros/planning_interface/ConfigExtras.cmake
Labels: backport-foxy, backport-galactic

#992 Doxygen support
  Doxyfile
  README.md
Labels: backport-foxy, backport-galactic

#1006 Set doxygen reference generation directory
  Doxyfile
Labels: backport-foxy, backport-galactic

#1009 Output html to a better directory
  Doxyfile
Labels: backport-foxy, backport-galactic

#591 Add moveit_configs_utils package to simplify loading paramters
  moveit2.repos
  moveit_configs_utils/moveit_configs_utils/__init__.py
  moveit_configs_utils/moveit_configs_utils/moveit_configs_builder.py
  moveit_configs_utils/package.xml
  moveit_configs_utils/resource/moveit_configs_utils
  moveit_configs_utils/setup.py
  moveit_kinematics/package.xml
  moveit_kinematics/test/launch/fanuc-kdl-singular.test.py
  moveit_kinematics/test/launch/fanuc-kdl.test.py
  moveit_kinematics/test/launch/fanuc-lma-singular.test.py
  moveit_kinematics/test/launch/fanuc-lma.test.py
  moveit_kinematics/test/launch/panda-kdl-singular.test.py
  moveit_kinematics/test/launch/panda-kdl.test.py
  moveit_kinematics/test/launch/panda-lma-singular.test.py
  moveit_kinematics/test/launch/panda-lma.test.py
  moveit_planners/pilz_industrial_motion_planner/package.xml
  moveit_planners/pilz_industrial_motion_planner/test/unit_tests/launch/common_parameters.py
  moveit_ros/benchmarks/examples/demo_panda.launch.py
  moveit_ros/benchmarks/examples/demo_panda_predefined_poses.launch.py
  moveit_ros/benchmarks/package.xml
  moveit_ros/moveit_servo/launch/pose_tracking_example.launch.py
  moveit_ros/moveit_servo/package.xml
  moveit_ros/moveit_servo/test/launch/servo_launch_test_common.py
  moveit_ros/moveit_servo/test/launch/test_servo_pose_tracking.test.py
  moveit_ros/moveit_servo/test/launch/unit_test_servo_calcs.test.py
  moveit_ros/planning_interface/package.xml
  moveit_ros/planning_interface/test/launch/move_group_launch_test_common.py
Labels: backport-galactic

#1020 Update moveit2.repos to ros2 for moveit_resources
  moveit2.repos
Labels: backport-galactic

#1018 Remove unused parameters.
  moveit_core/online_signal_smoothing/src/butterworth_filter.cpp
  moveit_core/planning_interface/src/planning_interface.cpp
  moveit_planners/chomp/chomp_interface/src/chomp_plugin.cpp
  moveit_planners/chomp/chomp_optimizer_adapter/src/chomp_optimizer_adapter.cpp
  moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/src/prbt_manipulator_ikfast_moveit_plugin.cpp
  moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/src/prbt_manipulator_ikfast_solver.cpp
  moveit_ros/benchmarks/src/BenchmarkOptions.cpp
  moveit_ros/hybrid_planning/hybrid_planning_manager/hybrid_planning_manager_component/src/hybrid_planning_manager.cpp
  moveit_ros/hybrid_planning/local_planner/local_constraint_solver_plugins/src/forward_trajectory.cpp
  moveit_ros/hybrid_planning/local_planner/trajectory_operator_plugins/src/simple_sampler.cpp
  moveit_ros/hybrid_planning/test/hybrid_planning_demo_node.cpp
  moveit_ros/move_group/src/default_capabilities/apply_planning_scene_service_capability.cpp
  moveit_ros/move_group/src/default_capabilities/cartesian_path_service_capability.cpp
  moveit_ros/move_group/src/default_capabilities/execute_trajectory_action_capability.cpp
  moveit_ros/move_group/src/default_capabilities/kinematics_service_capability.cpp
  moveit_ros/move_group/src/default_capabilities/plan_service_capability.cpp
  moveit_ros/move_group/src/default_capabilities/query_planners_service_capability.cpp
  moveit_ros/move_group/src/default_capabilities/state_validation_service_capability.cpp
  moveit_ros/moveit_servo/src/servo_node.cpp
  moveit_ros/moveit_servo/test/basic_servo_tests.cpp
  moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor.cpp
  moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/moveit_cpp.h
  moveit_ros/planning/planning_request_adapter_plugins/src/add_ruckig_traj_smoothing.cpp
  moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h
  moveit_ros/planning/planning_scene_monitor/test/trajectory_monitor_tests.cpp
  moveit_ros/visualization/motion_planning_rviz_plugin/src/interactive_marker_display.cpp
Labels: backport-galactic

#1027 Add missing test dependencies
  moveit_planners/pilz_industrial_motion_planner/package.xml
Labels: backport-galactic
