Repository moveit/moveit2, pull requests merged in 2025-01, with the labels that each got.

#3191 Fix: Conditionally install launch directory in generated MoveIt config package
  moveit_setup_assistant/moveit_setup_framework/templates/CMakeLists.txt
Labels: backport-humble, backport-jazzy

#3187 Fix planning_scene_monitor sync when passed empty robot state
  moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
Labels: backport-humble, backport-jazzy

#3206 Simplify scene update that does not include new robot_state
  moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
Labels: backport-humble, backport-jazzy

#3209 fix: OctoMap and Filtered_Cloud Not Updating During Movement Execution
  moveit_ros/perception/pointcloud_octomap_updater/include/moveit/pointcloud_octomap_updater/pointcloud_octomap_updater.hpp
  moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp
Labels: backport-humble, backport-jazzy

#3205 Don't destroy objects on attach
  moveit_core/planning_scene/src/planning_scene.cpp
  moveit_core/planning_scene/test/test_planning_scene.cpp
  moveit_ros/planning/plan_execution/src/plan_execution.cpp
Labels: backport-humble, backport-jazzy

#3217 Use ! in place of not keyword for Pilz and CHOMP planners
  moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp
  moveit_planners/pilz_industrial_motion_planner/include/joint_limits_copy/joint_limits_rosparam.hpp
Labels: backport-humble, backport-jazzy

#3219 pilz_industrial_motion_planner: Use tf2::fromMsg instead of tf2::convert
  moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp
Labels: backport-humble, backport-jazzy

#3229 fix chomp depend, closes #3228
  moveit_planners/moveit_planners/package.xml
Labels: backport-humble, backport-jazzy

#3232 Update packages table in README
  README.md
Labels: backport-jazzy

#3226 move TrajectoryExecutionManager::clear() to private
  moveit_py/src/moveit/moveit_ros/trajectory_execution_manager/trajectory_execution_manager.cpp
  moveit_ros/move_group/src/default_capabilities/execute_trajectory_action_capability.cpp
  moveit_ros/planning/plan_execution/src/plan_execution.cpp
  moveit_ros/planning/trajectory_execution_manager/include/moveit/trajectory_execution_manager/trajectory_execution_manager.hpp
Labels: backport-humble, backport-jazzy

#3198 [moveit_ros] fix race condition when stopping trajectory execution
  moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
Labels: backport-humble, backport-jazzy, backport-moveit1

#3227 Remove plugins from export set
  moveit_core/CMakeLists.txt
  moveit_kinematics/CMakeLists.txt
  moveit_kinematics/cached_ik_kinematics_plugin/CMakeLists.txt
  moveit_ros/move_group/CMakeLists.txt
Labels: backport-humble, backport-jazzy

#3249 Explicit convert from std::filesystem::path to std::string for Windows compatibility
  moveit_setup_assistant/moveit_setup_assistant/src/collisions_updater.cpp
  moveit_setup_assistant/moveit_setup_assistant/src/setup_assistant_widget.cpp
  moveit_setup_assistant/moveit_setup_core_plugins/include/moveit_setup_core_plugins/configuration_files.hpp
  moveit_setup_assistant/moveit_setup_core_plugins/src/configuration_files_widget.cpp
  moveit_setup_assistant/moveit_setup_core_plugins/src/start_screen.cpp
  moveit_setup_assistant/moveit_setup_core_plugins/src/start_screen_widget.cpp
  moveit_setup_assistant/moveit_setup_framework/include/moveit_setup_framework/data/srdf_config.hpp
  moveit_setup_assistant/moveit_setup_framework/src/srdf_config.cpp
  moveit_setup_assistant/moveit_setup_framework/src/urdf_config.cpp
  moveit_setup_assistant/moveit_setup_framework/src/utilities.cpp
Labels: backport-humble, backport-jazzy

#3255 Update includes for generate_parameter_library 0.4.0
  moveit_core/online_signal_smoothing/include/moveit/online_signal_smoothing/acceleration_filter.hpp
  moveit_core/online_signal_smoothing/include/moveit/online_signal_smoothing/butterworth_filter.hpp
  moveit_core/online_signal_smoothing/include/moveit/online_signal_smoothing/ruckig_filter.hpp
  moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/cached_ik_kinematics_plugin.hpp
  moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp
  moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/kdl_kinematics_plugin.hpp
  moveit_kinematics/srv_kinematics_plugin/include/moveit/srv_kinematics_plugin/srv_kinematics_plugin.hpp
  moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/command_list_manager.hpp
  moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/limits_container.hpp
  moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/pilz_industrial_motion_planner.hpp
  moveit_planners/pilz_industrial_motion_planner/src/command_list_manager.cpp
  moveit_planners/pilz_industrial_motion_planner/src/pilz_industrial_motion_planner.cpp
  moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_generator_common.cpp
  moveit_planners/stomp/include/stomp_moveit/stomp_moveit_planning_context.hpp
  moveit_planners/stomp/src/stomp_moveit_planning_context.cpp
  moveit_planners/test_configs/prbt_ikfast_manipulator_plugin/src/prbt_manipulator_ikfast_moveit_plugin.cpp
  moveit_ros/hybrid_planning/hybrid_planning_manager/hybrid_planning_manager_component/src/hybrid_planning_manager.cpp
  moveit_ros/hybrid_planning/local_planner/local_planner_component/src/local_planner_component.cpp
  moveit_ros/moveit_servo/include/moveit_servo/collision_monitor.hpp
  moveit_ros/moveit_servo/include/moveit_servo/servo.hpp
  moveit_ros/moveit_servo/include/moveit_servo/utils/common.hpp
  moveit_ros/planning/kinematics_plugin_loader/include/moveit/kinematics_plugin_loader/kinematics_plugin_loader.hpp
  moveit_ros/planning/planning_pipeline/include/moveit/planning_pipeline/planning_pipeline.hpp
  moveit_ros/planning/planning_request_adapter_plugins/src/check_for_stacked_constraints.cpp
  moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_bounds.cpp
  moveit_ros/planning/planning_request_adapter_plugins/src/check_start_state_collision.cpp
  moveit_ros/planning/planning_request_adapter_plugins/src/validate_workspace_bounds.cpp
  moveit_ros/planning/planning_response_adapter_plugins/src/add_time_optimal_parameterization.cpp
  moveit_ros/planning/planning_response_adapter_plugins/src/display_motion_path.cpp
  moveit_ros/planning/planning_response_adapter_plugins/src/validate_path.cpp
Labels: backport-jazzy

#3259 Reduce mutex scope in Servo thread
  moveit_ros/moveit_servo/src/servo_node.cpp
Labels: backport-jazzy

#3263 Fix: misleading error logs in RobotState::setFromIKSubgroups()
  moveit_core/robot_state/src/robot_state.cpp
Labels: backport-humble, backport-jazzy

#3274 Use attached object colors as is in Rviz plugin
  moveit_ros/visualization/rviz_plugin_render_tools/src/robot_state_visualization.cpp
Labels: backport-humble, backport-jazzy
